project:
  type: website

website:
  title: "Junyi Chu"
  navbar:
    right:
      - publications.qmd
      - cv.qmd
      - contact.qmd
  bread-crumbs: false
  page-footer: 
    left: "Copyright 2024, Junyi Chu"
    background: dark
    right: "Edit"
  repo-url: https://github.com/jchu10/jchu10.github.io
  repo-actions: [edit]
  favicon: assets/favico.ico
  twitter-card: 
    creator: "@junyichu"
  
format:
  html:
    theme: simplex
    css: styles.css
    toc: true